version: '3'
services:
  db:
    image: percona:ps-8.0
    container_name: mysql
    user: root
    networks:
      - lamp-docker
    environment:
      MYSQL_DATABASE: lamp_docker
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: proj_docker
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: 'Asia/Hong_Kong'
    # command: mysqld --user=root 
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
      - "./mysql/config/my.cnf:/etc/my.cnf"
    ports:
      - '3306:3306'
    restart: always
  elasticsearch:
    image: elasticsearch:7.14.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node  
  kibana:
    image: kibana:7.14.2
    container_name: kibana
    ports:
      - "5601:5601"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    networks:
      - lamp-docker
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
  mysqlexporter:
    container_name: mysql_exporter
    image: prom/mysqld-exporter
    ports: 
      - "9104:9104"
    environment: 
      - DATA_SOURCE_NAME=root:secret@(db)/lamp_docker
    networks:
      - lamp-docker
    expose:
      - 9104
    depends_on:
      - db
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    depends_on:
      - mysqlexporter
    networks:
      - lamp-docker
  php_apache:
    build: .
    image: php:8.1.12-apache
    container_name: php
    networks:
      - lamp-docker
    volumes:
      - "./src:/var/www/html"
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - lamp-docker
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
volumes:
  elastic_data: {}
networks:
  lamp-docker:
    driver: bridge