groups:
- name: Server_Alert
  rules:
  - alert: MySQL_Server_IsDown
    expr: mysql_up == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: MYSQL server is down
      description: "MySQL instance is down."
  - alert: MySQL_Server_Slow_Queries
    expr: increase(mysql_global_status_slow_queries[1m]) > 0
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: MySQL slow queries happened
      description: "MySQL server has some slow query."
  - alert: MySQL_Server_Restarted
    expr: mysql_global_status_uptime < 60
    for: 0m
    labels:
      serverity: info
    annotations:
      summary: MySQL has restarted
      description: "MysQL has benn restarted, which is less than one minute ago"
  - alert: MySQL_Too_Many_Connections
    expr: max_over_time(mysql_global_status_threads_connected[1m]) / mysql_global_variables_max_connections * 100 > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: MySQL's connections are more than 80%
      description: "More than 80% of MySQL connections are in use"

