global:
  scrape_interval: 1m

rule_files:
  - 'prometheys.rules.yml'
  - 'alerting.rules.yml'
  
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "mysql_metrics"
    static_configs:
    - targets: ["mysqlexporter:9104"]

